version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '5050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
